### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by cmpsoares91** [Irrelon/node-irrelon-router#4]
Hey thanks for the nice app, I was trying to use it but I get the following error:
```sh
$node router.js
Router table config data updated successfully.

Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

To add I've changed the port to 8080 because I got a redirect from port 80 to 8080 and I'm using the following config:
```sh
$cat config.js
routerTable = {};
routerTable['status.quantbull.com'] = { target: 'http://195.154.240.241:9000/' }
routerTable['health.quantbull.com'] = { target:'http://195.154.240.241:9000' }
routerTable['log.quantbull.com'] = { target:'http://195.154.240.241:9615' }
routerTable['dev.quantbull.com'] = { target:'http://195.154.240.241:8000' }
routerTable['beta.quantbull.com'] = { target:'http://195.154.240.241:8000' }
routerTable['www.quantbull.com'] = { target:'http://195.154.240.241:8000' }
```

My ports:
```sh
$sudo netstat -ntlp | grep LISTEN
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      875/named
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      767/sshd
tcp        0      0 127.0.0.1:953           0.0.0.0:*               LISTEN      875/named
tcp6       0      0 :::22                   :::*                    LISTEN      767/sshd
tcp6       0      0 ::1:953                 :::*                    LISTEN      875/named
```

How can I solve this?

Thank you very much in advance!

**Comment by Irrelon** [comment]
I've updated the repo to include more useful errors. Hopefully this will show you what is happening.
